name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run OpenLane2 Flow to Generate GDS
        uses: TinyTapeout/tt-gds-action@tt10
        with:
          flow: openlane2  # Use OpenLane2

      - name: Debug - List Generated Files
        run: find . -type f | tee file_list.txt

      - name: Upload File List (Debugging)
        uses: actions/upload-artifact@v4
        with:
          name: file-list
          path: file_list.txt

      - name: Upload GDS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds-file
          path: "**/*.gds"

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt10

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Gate-Level Simulation
        uses: TinyTapeout/tt-gds-action/gl_test@tt10

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GDS Viewer
        uses: TinyTapeout/tt-gds-action/viewer@tt10

